blank_issues_enabled: false
contact_links:
  - name: 📖 LMTagScript Documentation
    url: https://github.com/alexmoncks/lmtagscript#readme
    about: Please read the documentation before opening an issue.
  - name: 💬 Discussions
    url: https://github.com/alexmoncks/lmtagscript/discussions
    about: Ask questions and share ideas with the community.
  - name: 📚 Contributing Guide
    url: https://github.com/alexmoncks/lmtagscript/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to LMTagScript. 